local gazhuas = {}

function init(self)
    msg.post(".", "acquire_input_focus")
    self.speed = 100
end

function on_input(self, action_id, action)
    if action_id == hash("touch") and action.pressed then
        print("Touch!")
        local ga_id = factory.create("/go1#factory_gazhua", vmath.vector3(math.random(640), 0, 0))
        table.insert(gazhuas, ga_id)
    end
end

function update(self, dt)
    for k, v in pairs(gazhuas) do
        
    end
end